require_relative 'hdea_suite/report_creation_group'
require_relative 'hdea_suite/must_support_group'



module CancerRegistryReportingTestKit
  class HDEASuite < Inferno::TestSuite
    id :ccrr_hdea
    title 'Cancer Registry Reporting Health Data Exchange App (HDEA) Test Suite'
    short_title 'CCRR Health Data Exchange App (HDEA)'
    description '
    The Cancer Registry Reporting HDEA Test Suite verifies the 
    conformance of Health Data Exchange Apps to the STU 1.0.0 version of the HL7® FHIR® 
    [Central Cancer Registry Reporting IG](https://hl7.org/fhir/us/central-cancer-registry-reporting/STU1/).
    
    ## Scope
    
    These tests are a DRAFT intended to allow payer implementers to perform preliminary checks of their systems against CCRR IG requirements.
    Future versions of these tests may validate other requirements and may change the test validation logic.

    ## Test Methodology
    
    Inferno takes the content bundle(s) generated by the HDEA, checking that resources included are conformant to corresponding profiles
    and include all MS elements. Resources covered include those explicitly marked MS within the 
    [report composition](https://hl7.org/fhir/us/central-cancer-registry-reporting/STU1/StructureDefinition-ccrr-composition.html).

    ## Current Limitations
    
    Current tests do not verify the ability of the HDEA to gather data from an EHR and transmit that information as a report to registries.
    Because of this, tests do not cover reporting bundles or message headers, which are used for report transmission.
    '

    links [
      # {
      #   label: 'Report Issue',
      #   url: 'https://github.com/inferno-framework/cancer-registry-reporting-test-kit/issues'
      # },
      # {
      #   label: 'Open Source',
      #   url: 'https://github.com/inferno-framework/cancer-registry-reporting-test-kit'
      # },
      # {
      #   label: 'Download',
      #   url: 'https://github.com/inferno-framework/cancer-registry-reporting-test-kit/releases'
      # },
      {
        label: 'Implementation Guide',
        url: 'https://hl7.org/fhir/us/central-cancer-registry-reporting/STU1/'
      }
    ]

    # All FHIR validation requests will use this FHIR validator
    fhir_resource_validator do
      igs 'hl7.fhir.us.central-cancer-registry-reporting#1.0.0', 'hl7.fhir.us.core#3.1.1'

      exclude_message do |message|
        message.message.match?(/\A\S+: \S+: URL value '.*' does not resolve/)
      end
    end

    group from: :ccrr_hdea_report_creation
    group from: :ccrr_hdea_must_support

  end
end