require_relative 'must_support_group/content_bundle_must_support_test'
require_relative 'must_support_group/report_composition_must_support_test'
require_relative 'must_support_group/report_resources_must_support_test'


module CancerRegistryReportingTestKit
  class HDEAReportMustSupportGroup < Inferno::TestGroup
    title 'Health Data Exchange App Must Support Group'
    id :ccrr_hdea_must_support
    description %(
    Tests verify that cancer reports generated by the HDEA include all elements marked Must Support within
    [Central Cancer Registry IG v1.0.0](https://hl7.org/fhir/us/central-cancer-registry-reporting/STU1/) and
    implementation guides that the CCRR relies upon. These are [US Core](http://hl7.org/fhir/us/core/STU3.1.1/index.html) (or within the CCRR IG and derived from US Core), 
    [mCode](http://hl7.org/fhir/us/mcode/STU3/index.html), and 
    [Occupational Data for Health](http://hl7.org/fhir/us/odh/STU1.1/index.html).

    Currently, report bundle(s) must be provided manually after being generated by the HDEA under test.
    )

    input :reports,
    title: 'Cancer Reports',
    description: 'List of Content Bundle(s)'

    test from: :ccrr_hdea_content_bundle_must_support_test
    test from: :ccrr_hdea_report_composition_must_support_test
    test from: :ccrr_hdea_report_resources_must_support_test

  end
end