require_relative 'must_support_group/cancer_encounter_must_support_test'
require_relative 'must_support_group/cancer_patient_must_support_test'
require_relative 'must_support_group/composition_must_support_test'
require_relative 'must_support_group/ccrr_content_bundle_must_support_test'
require_relative 'must_support_group/plan_definition_must_support_test'
require_relative 'must_support_group/ccrr_reporting_bundle_must_support_test'
require_relative 'must_support_group/central_cancer_registry_primary_cancer_condition_must_support_test'
require_relative 'must_support_group/message_header_must_support_test'
require_relative 'must_support_group/us_ph_patient_must_support_test'
require_relative 'must_support_group/extension_must_support_test'
require_relative 'must_support_group/medication_administration_must_support_test'
require_relative 'must_support_group/mcode_radiotherapy_course_summary_must_support_test'
require_relative 'must_support_group/mcode_secondary_cancer_condition_must_support_test'
require_relative 'must_support_group/mcode_tnm_stage_group_must_support_test'
require_relative 'must_support_group/odh_usual_work_must_support_test'
require_relative 'must_support_group/allergy_intolerance_must_support_test'
require_relative 'must_support_group/care_plan_must_support_test'
require_relative 'must_support_group/document_reference_must_support_test'
require_relative 'must_support_group/encounter_must_support_test'
require_relative 'must_support_group/medication_must_support_test'
require_relative 'must_support_group/organization_must_support_test'
require_relative 'must_support_group/patient_must_support_test'
require_relative 'must_support_group/practitioner_must_support_test'
require_relative 'must_support_group/practitioner_role_must_support_test'
require_relative 'must_support_group/procedure_must_support_test'
require_relative 'must_support_group/smokingstatus_must_support_test'
module CancerRegistryReportingTestKit
  class HDEAReportMustSupportGroup < Inferno::TestGroup
    title 'Health Data Exchange App Must Support Group'
    id :ccrr_hdea_must_support
    description %(
    Tests verify that cancer reports generated by the HDEA include all elements marked Must Support within
    [Central Cancer Registry IG v1.0.0](https://hl7.org/fhir/us/central-cancer-registry-reporting/STU1/) and
    implementation guides that the CCRR relies upon. These are [US Core](http://hl7.org/fhir/us/core/STU3.1.1/index.html) (or within the CCRR IG and derived from US Core), 
    [mCode](http://hl7.org/fhir/us/mcode/STU3/index.html), and 
    [Occupational Data for Health](http://hl7.org/fhir/us/odh/STU1.1/index.html).

    Currently, report bundle(s) must be provided manually after being generated by the HDEA under test.
    )

    input :reports,
    title: 'Cancer Reports',
    description: 'List of Content Bundle(s)'

    test from: :ccrr_v100_ccrr_content_bundle_must_support_test
    test from: :ccrr_v100_cancer_encounter_must_support_test
    test from: :ccrr_v100_cancer_patient_must_support_test
    test from: :ccrr_v100_composition_must_support_test
    test from: :ccrr_v100_plan_definition_must_support_test
    # test from: :ccrr_v100_ccrr_reporting_bundle_must_support_test
    test from: :ccrr_v100_central_cancer_registry_primary_cancer_condition_must_support_test
    # test from: :ccrr_v100_message_header_must_support_test
    test from: :ccrr_v100_us_ph_patient_must_support_test
    test from: :ccrr_v100_extension_must_support_test
    test from: :ccrr_v100_medication_administration_must_support_test
    test from: :ccrr_v100_mcode_radiotherapy_course_summary_must_support_test
    test from: :ccrr_v100_mcode_secondary_cancer_condition_must_support_test
    test from: :ccrr_v100_mcode_tnm_stage_group_must_support_test
    test from: :ccrr_v100_odh_usual_work_must_support_test
    test from: :ccrr_v100_allergy_intolerance_must_support_test
    test from: :ccrr_v100_care_plan_must_support_test
    test from: :ccrr_v100_document_reference_must_support_test
    test from: :ccrr_v100_encounter_must_support_test
    test from: :ccrr_v100_medication_must_support_test
    test from: :ccrr_v100_organization_must_support_test
    test from: :ccrr_v100_patient_must_support_test
    test from: :ccrr_v100_practitioner_must_support_test
    test from: :ccrr_v100_practitioner_role_must_support_test
    test from: :ccrr_v100_procedure_must_support_test
    test from: :ccrr_v100_smokingstatus_must_support_test

  end
end