require_relative 'report_creation_group/content_bundle_validation_test'
require_relative 'report_creation_group/report_resources_validation_test'


module CancerRegistryReportingTestKit
  class HDEAReportCreationGroup < Inferno::TestGroup
    title 'Health Data Exchange App Report Creation'
    id :ccrr_hdea_report_creation
    description %(
    Tests verify that a single cancer report (content bundle) is appropriately packaged by the HDEA and conformant to profile in the 
    [Central Cancer Registry IG v1.0.0](https://hl7.org/fhir/us/central-cancer-registry-reporting/STU1/). These include the
    [Content Bundle](https://build.fhir.org/ig/HL7/fhir-central-cancer-registry-reporting-ig/StructureDefinition-ccrr-content-bundle.html), 
    [Report Composition](https://build.fhir.org/ig/HL7/fhir-central-cancer-registry-reporting-ig/StructureDefinition-ccrr-composition.html), 
    and the entries in the bundle. The resources in the bundle may come from 
    [US Core](http://hl7.org/fhir/us/core/STU3.1.1/index.html) (or within the CCRR IG and derived from US Core), 
    [mCode](http://hl7.org/fhir/us/mcode/STU3/index.html), and 
    [Occupational Data for Health](http://hl7.org/fhir/us/odh/STU1.1/index.html).

    The reference resolution test verifies that resources referenced in the composition, are 
    present in the content bundle.

    Currently, the report bundle must be provided manually after being generated by the HDEA under test.
    )

    input :single_report,
    title: 'Cancer Report',
    description: 'A single Content Bundle'

    test from: :ccrr_hdea_content_bundle_validation_test
    test from: :ccrr_hdea_report_resources_validation_test

  end
end