require_relative 'report_creation_group/content_bundle_validation_test'
require_relative 'report_creation_group/cancer_encounter_validation_test'
require_relative 'report_creation_group/cancer_patient_validation_test'
require_relative 'report_creation_group/plan_definition_validation_test'
require_relative 'report_creation_group/central_cancer_registry_primary_cancer_condition_validation_test'
require_relative 'report_creation_group/message_header_validation_test'
require_relative 'report_creation_group/us_ph_patient_validation_test'
require_relative 'report_creation_group/extension_validation_test'
require_relative 'report_creation_group/medication_administration_validation_test'
require_relative 'report_creation_group/mcode_radiotherapy_course_summary_validation_test'
require_relative 'report_creation_group/mcode_secondary_cancer_condition_validation_test'
require_relative 'report_creation_group/mcode_tnm_stage_group_validation_test'
require_relative 'report_creation_group/odh_usual_work_validation_test'
require_relative 'report_creation_group/allergy_intolerance_validation_test'
require_relative 'report_creation_group/care_plan_validation_test'
require_relative 'report_creation_group/document_reference_validation_test'
require_relative 'report_creation_group/encounter_validation_test'
require_relative 'report_creation_group/medication_validation_test'
require_relative 'report_creation_group/organization_validation_test'
require_relative 'report_creation_group/patient_validation_test'
require_relative 'report_creation_group/practitioner_validation_test'
require_relative 'report_creation_group/practitioner_role_validation_test'
require_relative 'report_creation_group/procedure_validation_test'
require_relative 'report_creation_group/smokingstatus_validation_test'


module CancerRegistryReportingTestKit
  class HDEAReportCreationGroup < Inferno::TestGroup
    title 'Health Data Exchange App Report Creation'
    id :ccrr_hdea_report_creation
    description %(
    Tests verify that a single cancer report (content bundle) is appropriately packaged by the HDEA and conformant to profile in the 
    [Central Cancer Registry IG v1.0.0](https://hl7.org/fhir/us/central-cancer-registry-reporting/STU1/). These include the
    [Content Bundle](https://build.fhir.org/ig/HL7/fhir-central-cancer-registry-reporting-ig/StructureDefinition-ccrr-content-bundle.html), 
    [Report Composition](https://build.fhir.org/ig/HL7/fhir-central-cancer-registry-reporting-ig/StructureDefinition-ccrr-composition.html), 
    and the entries in the bundle. The resources in the bundle may come from 
    [US Core](http://hl7.org/fhir/us/core/STU3.1.1/index.html) (or within the CCRR IG and derived from US Core), 
    [mCode](http://hl7.org/fhir/us/mcode/STU3/index.html), and 
    [Occupational Data for Health](http://hl7.org/fhir/us/odh/STU1.1/index.html).

    The reference resolution test verifies that resources referenced in the composition, are 
    present in the content bundle.

    Currently, the report bundle must be provided manually after being generated by the HDEA under test.
    )

    input :single_report,
    title: 'Cancer Report',
    type: 'textarea',
    description: 'A single Content Bundle. This Content Bundle should include all of the referenced resources.'

    run_as_group

    # Commenting out some of these tests 
    test from: :ccrr_hdea_content_bundle_validation_test
    # test from: :ccrr_v100_cancer_encounter_validation_test
    # test from: :ccrr_v100_cancer_patient_validation_test
    test from: :ccrr_v100_plan_definition_validation_test
    test from: :ccrr_v100_central_cancer_registry_primary_cancer_condition_validation_test
    # test from: :ccrr_v100_message_header_validation_test
    # test from: :ccrr_v100_us_ph_patient_validation_test
    test from: :ccrr_v100_extension_validation_test
    test from: :ccrr_v100_medication_administration_validation_test
    test from: :ccrr_v100_mcode_radiotherapy_course_summary_validation_test
    test from: :ccrr_v100_mcode_secondary_cancer_condition_validation_test
    test from: :ccrr_v100_mcode_tnm_stage_group_validation_test
    test from: :ccrr_v100_odh_usual_work_validation_test
    test from: :ccrr_v100_allergy_intolerance_validation_test
    test from: :ccrr_v100_care_plan_validation_test
    test from: :ccrr_v100_document_reference_validation_test
    test from: :ccrr_v100_encounter_validation_test
    test from: :ccrr_v100_medication_validation_test
    test from: :ccrr_v100_organization_validation_test
    test from: :ccrr_v100_patient_validation_test
    test from: :ccrr_v100_practitioner_validation_test
    test from: :ccrr_v100_practitioner_role_validation_test
    test from: :ccrr_v100_procedure_validation_test
    test from: :ccrr_v100_smokingstatus_validation_test

  end
end